apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountservice
  template:
    metadata:
      labels:
        app: discountservice
    spec:
      containers:
        - name: discountservice
          image: purelengend/discountservice:latest
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
---
apiVersion: v1
kind: Service
metadata:
  name: discount-srv
spec:
  selector:
    app: discountservice
  ports:
    - name: discountservice
      port: 9000
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
